stages:
  - test
  - build
  - deploy

code_style:
  image: node:10-alpine
  stage: test
  script:
    - yarn
    - yarn lint

unit_test:
  image: node:10-alpine
  stage: test
  script:
    - yarn
    - yarn test

build-app:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_NAME: "app"
    CI_REGISTRY_IMAGE: "registry.gitlab.com/fastpay-pi2/products-api"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest -f ./docker/server.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
  tags:
    - docker
  only:
    - master

build-db:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_NAME: "db"
    CI_REGISTRY_IMAGE: "registry.gitlab.com/fastpay-pi2/products-api"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest -f ./docker/database.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
  tags:
    - docker
  only:
    - master
