version: "3"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: docker/server.Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  postgres:
    container_name: database
    build:
      context: ./
      dockerfile: docker/database.Dockerfile
    ports:
      - "5432:5432"