version: "3"

services:
  products_api:
    container_name: products_api
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    env_file:
      - .env
    depends_on:
      - products_db
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - fastpay-network
    ports:
      - "3000:3000"

  products_db:
    container_name: products_db
    build:
      context: .
      dockerfile: ./docker/database.Dockerfile
    networks:
      - fastpay-network
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  database-population:
    container_name: database_population
    build:
      context: .
      dockerfile: ./docker/database_population.Dockerfile
    volumes:
      - ./database_population/:/usr/src/app/
    networks:
      - fastpay-network
    depends_on:
      - products_api
    env_file:
      - .env
  
networks:
  fastpay-network:
    external: true
