version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  postgres:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/database.Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  database-population:
    container_name: database_population
    build:
      context: .
      dockerfile: ./docker/database_population.Dockerfile
    volumes:
      - ./database_population/:/usr/src/app/
    depends_on:
      - app
    env_file:
      - .env