version: "3"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db