CREATE TABLE CATEGORY (
	id serial PRIMARY KEY NOT NULL,
	name varchar(50) NOT NULL
);

CREATE TABLE SUBCATEGORY (
	id serial PRIMARY KEY NOT NULL,
	idCategory integer NOT NULL,
	name varchar(50) NOT NULL,

	CONSTRAINT SUBCATEGORY_CATEGORY_FK FOREIGN KEY (idCategory) REFERENCES CATEGORY (id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUCT (
	id serial PRIMARY KEY NOT NULL,
	name varchar(200) NOT NULL,
	brand varchar(100),
	image varchar(200),
	barcode varchar(13),
	price float(2) NOT NULL,
	idSubcategory integer,

	CONSTRAINT PRODUCT_SUBCATEGORY_FK FOREIGN KEY (idSubcategory) REFERENCES SUBCATEGORY (id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ITEM (
	rfid char(41) PRIMARY KEY,
	expirationDate DATE,
	idProduct integer,

	CONSTRAINT ITEM_PRODUCT_FK FOREIGN KEY (idProduct) REFERENCES PRODUCT (id) ON DELETE CASCADE
		ON UPDATE CASCADE
);
